import React, { useState } from 'react';
import { 
  Bot, 
  X, 
  Send, 
  Scale
} from 'lucide-react';

interface AIAssistantDrawerProps {
  isOpen: boolean;
  onClose: () => void;
}

interface Message {
  role: 'user' | 'assistant';
  text: string;
  citations?: { statute: string; section: string; text: string }[];
}

export const AIAssistantDrawer: React.FC<AIAssistantDrawerProps> = ({ isOpen, onClose }) => {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'assistant',
      text: "Namaste! I am the ShramAI Labour Compliance Intelligence Assistant. I provide statutory explanations strictly grounded in the Four Labour Codes of India, official gazette rules, and document evidence. How may I assist your audit today?",
      citations: [
        {
          statute: "Code on Wages, 2019",
          section: "Section 6 & Section 50",
          text: "Minimum wage floors and mandatory wage register maintenance."
        }
      ]
    }
  ]);
  const [input, setInput] = useState('');

  if (!isOpen) return null;

  const quickPrompts = [
    "Why was ABC Industries flagged as HIGH risk?",
    "What are the statutory overtime rules under the Code on Wages?",
    "Which documents must an employer keep under OSH&WC Code Section 33?",
    "What is the penalty for headcount discrepancies across muster rolls?",
  ];

  const handleSend = (textToSend?: string) => {
    const query = textToSend || input;
    if (!query.trim()) return;

    const userMsg: Message = { role: 'user', text: query };
    let assistantMsg: Message;

    if (query.toLowerCase().includes("abc industries") || query.toLowerCase().includes("flagged") || query.toLowerCase().includes("high risk")) {
      assistantMsg = {
        role: 'assistant',
        text: "ABC Industries Ltd. was flagged as HIGH RISK (Risk Score: 87/100) due to three high-severity issues: (1) 5 contract workers present in the Attendance Muster Roll are omitted from the Form B Wage Register, (2) Daily wage rates for 3 helpers fell below the statutory floor rate of Rs 350/day, and (3) Net payout on bank credit slips showed a deficit of Rs 52,600 compared to Form B records.",
        citations: [
          {
            statute: "Code on Wages, 2019",
            section: "Section 6(1)",
            text: "Payment of minimum rates of wages to all scheduled employments."
          },
          {
            statute: "Code on Wages, 2019",
            section: "Section 50(1)",
            text: "Every employer shall maintain registers of wages, muster roll and overtime."
          }
        ]
      };
    } else if (query.toLowerCase().includes("overtime")) {
      assistantMsg = {
        role: 'assistant',
        text: "Under Section 14 of the Code on Wages 2019, where an employee works in any employment on any day in excess of the number of hours constituting a normal working day, the employer shall pay them for every hour or part of an hour so worked in excess at the overtime rate, which shall not be less than twice the normal rate of wages.",
        citations: [
          {
            statute: "Code on Wages, 2019",
            section: "Section 14",
            text: "Wages for overtime work at not less than twice the normal rate."
          }
        ]
      };
    } else {
      assistantMsg = {
        role: 'assistant',
        text: `Regarding "${query}": Under the Four Labour Codes of India, employers are required to harmonize muster rolls, Form B wage sheets, and electronic payment records. All inspection prioritizations generated by ShramAI are calculated by calibrated ML risk engines with verifiable evidence references.`,
        citations: [
          {
            statute: "Central Labour Rules & Four Labour Codes",
            section: "Statutory Harmonization Provision",
            text: "Proactive compliance self-audits must maintain verifiable audit trails."
          }
        ]
      };
    }

    setMessages(prev => [...prev, userMsg, assistantMsg]);
    setInput('');
  };

  return (
    <div className="fixed inset-y-0 right-0 z-50 w-full max-w-lg bg-slate-900/95 border-l border-slate-800 shadow-2xl backdrop-blur-xl flex flex-col">
      
      {/* Drawer Header */}
      <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-300">
            <Bot className="w-4 h-4" />
          </div>
          <div>
            <h2 className="font-bold text-sm text-white">Labour Law AI Assistant</h2>
            <p className="text-[10px] text-slate-400 font-mono">Grounded in the Four Labour Codes</p>
          </div>
        </div>
        <button
          onClick={onClose}
          className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Messages List */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((msg, idx) => {
          const isAssistant = msg.role === 'assistant';
          return (
            <div
              key={idx}
              className={`flex flex-col ${isAssistant ? 'items-start' : 'items-end'}`}
            >
              <div
                className={`max-w-[90%] p-3.5 rounded-2xl text-xs leading-relaxed ${
                  isAssistant
                    ? 'bg-slate-800/90 text-slate-200 border border-slate-700/80 rounded-tl-sm'
                    : 'bg-blue-600 text-white rounded-tr-sm shadow-md shadow-blue-500/20'
                }`}
              >
                {msg.text}

                {/* Citations Box */}
                {msg.citations && msg.citations.length > 0 && (
                  <div className="mt-3 pt-2.5 border-t border-slate-700/60 space-y-1.5">
                    <span className="text-[10px] font-mono text-amber-400 font-semibold uppercase tracking-wider block">
                      Ground-Truth Legal Reference:
                    </span>
                    {msg.citations.map((c, cIdx) => (
                      <div key={cIdx} className="bg-slate-950/60 p-2 rounded border border-slate-800 space-y-0.5">
                        <div className="flex items-center gap-1 text-[11px] text-amber-300 font-semibold">
                          <Scale className="w-3 h-3" />
                          <span>{c.statute} — {c.section}</span>
                        </div>
                        <p className="text-[10px] text-slate-400 italic">"{c.text}"</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Suggested Prompts */}
      <div className="p-3 border-t border-slate-800/80 bg-slate-950/40 space-y-1.5">
        <span className="text-[10px] text-slate-500 font-mono block">QUICK COMPLIANCE QUERIES:</span>
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1">
          {quickPrompts.map((q, idx) => (
            <button
              key={idx}
              onClick={() => handleSend(q)}
              className="px-2.5 py-1 rounded-lg bg-slate-800/60 hover:bg-slate-800 text-slate-300 hover:text-white border border-slate-700/60 text-[11px] whitespace-nowrap transition"
            >
              {q}
            </button>
          ))}
        </div>
      </div>

      {/* Input Box */}
      <div className="p-3 border-t border-slate-800 bg-slate-950 flex items-center gap-2">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSend()}
          placeholder="Ask about labour code rules, penalties, or audit findings..."
          className="flex-1 px-3 py-2 rounded-xl bg-slate-900 border border-slate-800 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-purple-500"
        />
        <button
          onClick={() => handleSend()}
          className="p-2 rounded-xl bg-purple-600 hover:bg-purple-500 text-white transition shadow-md shadow-purple-600/20"
        >
          <Send className="w-4 h-4" />
        </button>
      </div>

    </div>
  );
};
